CREATE TABLE cook_steps (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- 조리방법 ID
    recipe_id NUMBER REFERENCES recipes(id) ON DELETE CASCADE,      -- 레시피 ID, 삭제 시 자동 삭제
    step_text VARCHAR2(1000),                                       -- 조리 방법
    step_order NUMBER                                               -- 조리 순서
);

SELECT * FROM cook_steps;