CREATE TABLE ingredients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,         -- 재료 ID
    recipe_id NUMBER REFERENCES recipes(id) ON DELETE CASCADE,      -- 레시피 ID, 삭제 시 관련 재료 / 조리법도 자동 삭제
    ingredient_text VARCHAR2(200)                                   -- 재료
);

SELECT * FROM ingredients;