CREATE TABLE recipes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 레시피 ID, 자동 증가
    name VARCHAR2(100) NOT NULL,                            -- 레시피 이름(공백 불가)
    category VARCHAR2(100),                                 -- 카테고리
    fileName VARCHAR2(50)                                   -- 이미지 이름
);

INSERT INTO recipes(name, category, fileName) VALUES('새송이버섯버터굴소스볶음', '볶음 요리', 'resources/images/food-1.jpg');
INSERT INTO recipes(name, category, fileName) VALUES('순두부찜', '찜 요리', 'resources/images/food-2.jpg');

SELECT * FROM RECIPES;

DROP TABLE RECIPES;
DROP TABLE INGREDIENTS;

SELECT * FROM v$version;

CREATE TABLE TEST(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_now DATE DEFAULT SYSDATE,
    json JSON
);

DESC TEST;

DROP TABLE TEST;

INSERT INTO TEST(json) VALUES('');

INSERT INTO TEST(json) VALUES ('
{
  "image": "resources/images/food-1.jpg",
  "name": "새송이버섯버터굴소스볶음",
  "category": "볶음 요리",
  "ingredient": [
    "미니새송이버섯 : 1팩",
    "버터 : 20g",
    "굴소스 : 1T",
    "진간장 : 0.5T",
    "통깨 약간"
  ],
  "cook": [
    "새송이버섯은 길게 편 썰기한다.",
    "팬을 달군 후 버터 20그램을 녹인다.",
    "버터가 녹으면 새송이 버섯을 넣고 볶는다.",
    "버섯이 반쯤 익었을 때 굴소스 1스푼 넣는다.",
    "진간장도 0.5T 넣는다.",
    "통깨도 넣어서 섞는다."
  ]
}');

SELECT * FROM TEST;

SELECT
    id,
    JSON_VALUE(json, '$.image') AS image,
    JSON_VALUE(json, '$.name')  AS name,
    JSON_VALUE(json, '$.category') AS category,
    JSON_QUERY(json, '$.ingredient') AS ingredient,
    JSON_QUERY(json, '$.cook') AS cook
FROM TEST;


CREATE TABLE recipes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 레시피 ID, 자동 증가
    name VARCHAR2(100) NOT NULL,                            -- 레시피 이름(공백 불가)
    category VARCHAR2(100),                                 -- 카테고리
    fileName VARCHAR2(50)                                   -- 이미지 이름
);

CREATE TABLE recipes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    json json
)