CREATE TABLE recipes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 레시피 ID, 자동 증가
    name VARCHAR2(200) NOT NULL,                            -- 레시피 이름(공백 불가)
    category VARCHAR2(100),                                 -- 카테고리
    fileName VARCHAR2(30)                                   -- 이미지 이름
);

select * from recipes;

desc recipes;