CREATE TABLE recipe (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_now DATE DEFAULT SYSDATE,
    member_id VARCHAR2(20),
    json JSON
);

ALTER TABLE recipe 
ADD CONSTRAINT cons_f1
FOREIGN KEY (member_id)
REFERENCES member(id);

--제약조건 확인
SELECT * FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TEST'
    AND CONSTRAINT_TYPE = 'R';


SELECT * FROM RECIPE;

delete recipe where id = 23;

DESC RECIPE;

INSERT INTO recipe(member_id, json) VALUES ('admin', q'[
{
  "image": "resources/images/food-1.jpg",
  "name": "새송이버섯버터굴소스볶음",
  "category": "한식",
  "ingredient": [
    "미니새송이버섯 : 1팩",
    "버터 : 20g",
    "굴소스 : 1T",
    "진간장 : 0.5T",
    "통깨 약간"
  ],
  "cook": [
    "새송이버섯은 길게 편 썰기한다.",
    "팬을 달군 후 버터 20그램을 녹인다.",
    "버터가 녹으면 새송이 버섯을 넣고 볶는다.",
    "버섯이 반쯤 익었을 때 굴소스 1스푼 넣는다.",
    "진간장도 0.5T 넣는다.",
    "통깨도 넣어서 섞는다."
  ]
}
]');


INSERT INTO recipe(member_id, json) VALUES ('admin', q'[
{
  "image": "resources/images/food-1.jpg",
  "name": "테스트용",
  "category": "디저트",
  "ingredient": [
    "미니새송이버섯 : 1팩",
    "버터 : 20g",
    "굴소스 : 1T",
    "진간장 : 0.5T",
    "통깨 약간"
  ],
  "cook": [
    "새송이버섯은 길게 편 썰기한다.",
    "팬을 달군 후 버터 20그램을 녹인다.",
    "버터가 녹으면 새송이 버섯을 넣고 볶는다.",
    "버섯이 반쯤 익었을 때 굴소스 1스푼 넣는다.",
    "진간장도 0.5T 넣는다.",
    "통깨도 넣어서 섞는다."
  ]
}
]');
commit;


-- DROP TABLE recipe;