CREATE TABLE member(
    id VARCHAR2(20) PRIMARY KEY,
    password VARCHAR2(20) NOT NULL,
    name VARCHAR2(10) NOT NULL,
    gendar VARCHAR(4),
    birth VARCHAR2(10),
    mail VARCHAR2(30),
    phone VARCHAR2(20),
    address VARCHAR2(90),
    regist_day DATE DEFAULT SYSDATE
);

ALTER TABLE member
    MODIFY regist_day DATE DEFAULT SYSDATE;

CREATE TABLE recipe (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_now DATE DEFAULT SYSDATE,
    member_id VARCHAR2(20),
    json JSON
);

ALTER TABLE recipe 
ADD CONSTRAINT cons_f1
FOREIGN KEY (member_id)
REFERENCES member(id);

--제약조건 확인
SELECT * FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'TEST'
    AND CONSTRAINT_TYPE = 'R';


SELECT * FROM RECIPE;
SELECT * FROM MEMBER;

DESC RECIPE
DESC member;

DROP TABLE recipe;
DROP TABLE MEMBER;

INSERT INTO member VALUES('admin', 'admin1234', '관리자', null, null, null, null, null, null);
INSERT INTO member(id, password, name, gender, birth, mail, phone, address) VALUES('TEST', 'TEST1234', '테스트', '남', '2001-01-02', 'test@gmail.com', '010-1234-5678', '울산');

DELETE member WHERE id = 'TEST';

INSERT INTO recipe(member_id, json) VALUES ('admin', q'[
{
  "image": "resources/images/food-1.jpg",
  "name": "새송이버섯버터굴소스볶음",
  "category": "볶음 요리",
  "ingredient": [
    "미니새송이버섯 : 1팩",
    "버터 : 20g",
    "굴소스 : 1T",
    "진간장 : 0.5T",
    "통깨 약간"
  ],
  "cook": [
    "새송이버섯은 길게 편 썰기한다.",
    "팬을 달군 후 버터 20그램을 녹인다.",
    "버터가 녹으면 새송이 버섯을 넣고 볶는다.",
    "버섯이 반쯤 익었을 때 굴소스 1스푼 넣는다.",
    "진간장도 0.5T 넣는다.",
    "통깨도 넣어서 섞는다."
  ]
}
]');
commit;
