CREATE TABLE Member(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(128) NOT NULL,
    email VARCHAR2(256) NOT NULL UNIQUE,
    age NUMBER
);

INSERT INTO Member(name, email, age) VALUES('윤서준', 'Seojunyoon@hanbit.co.kr', 10);
INSERT INTO Member(name, email, age) VALUES('윤광철', 'KwangcheolYoon@hanbit.co.kr', 43);
INSERT INTO Member(name, email, age) VALUES('공미영', 'MiyeongKong@hanbit.co.kr', 23);
INSERT INTO Member(name, email, age) VALUES('김도윤', 'DoyunKim@hanbit.co.kr', 10);


SELECT * FROM Member;

commit;